server:
  port: 5154
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  jwt:
    secret: h7J2jZ4Bp8WvE9RfTcYvD1QaL6OzXsCmIuN5rFwTgPqM1eCvK9jX4eTcYvU3xS6z
  datasource:
    url: jdbc:mariadb://localhost:3306/jeonga?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: jeonga
    password: test1234
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

